-- DropForeignKey
ALTER TABLE "Users" DROP CONSTRAINT "Users_roleID_fkey";

-- DropForeignKey
ALTER TABLE "Users" DROP CONSTRAINT "Users_teamID_fkey";

-- AlterTable
ALTER TABLE "Users" ALTER COLUMN "DOB" DROP NOT NULL,
ALTER COLUMN "Gender" DROP NOT NULL,
ALTER COLUMN "teamID" DROP NOT NULL,
ALTER COLUMN "roleID" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "Users" ADD CONSTRAINT "Users_teamID_fkey" FOREIGN KEY ("teamID") REFERENCES "Team"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Users" ADD CONSTRAINT "Users_roleID_fkey" FOREIGN KEY ("roleID") REFERENCES "Role"("ID") ON DELETE SET NULL ON UPDATE CASCADE;
