const express = require("express");
const dotenv = require("dotenv").config();
const cookieParser = require("cookie-parser");
const prisma = require("./prismaClient");
const schedule = require("node-schedule");
const path = require("path");
const cors = require("cors");
const userRouter = require("./routes/api/UserRoute");
const roleRouter = require("./routes/api/RoleRoute");
const resourceRouter = require("./routes/api/ResourcesRoute");
const teamRouter = require("./routes/api/TeamRoute");
const AuthRouter = require("./routes/api/AuthRoute");
const credentials = require("./middlewares/credentials");
const roleResourceRouter = require("./routes/api/RoleResourcesRoute");
const languageRouter = require("./routes/api/LanguageRouter");
const articleRouter = require("./routes/api/ArticlesRoute");
const corsOptions = require("./config/corsOptions");
const addressRouter = require("./routes/api/AddressRoute");
const unitRouter = require("./routes/api/UnitRoute");
const currencyRouter = require("./routes/api/CurrencyRoute");
const developerRouter = require("./routes/api/DeveloperRoute");
const categoryRouter = require("./routes/api/CategoryRoute");
const announcementRouter = require("./routes/api/AnnouncementRoute");
const aminitiesRouter = require("./routes/api/AminitiesRoute");
const propertyRouter = require("./routes/api/PropertyRoute");
const guestRouter = require("./routes/api/GuestInfoRoute");
const MetaDataRouter = require("./routes/api/MetaDataRoute");
const feedbackRouter = require("./routes/api/FeedbackRoute");
const enquiryFormRouter = require("./routes/api/EnquiryFormRoute");
const listwithusRouter = require("./routes/api/ListWithUsRoute");
const jobRouter = require("./routes/api/JobRoute");
const applicantRouter = require("./routes/api/ApplicationRoute");
const { errorHandler } = require("./middlewares/ErrorHandler");
const { logger } = require("./middlewares/logEvents");
const { CronJob } = require("./middlewares/CronJobs");
const paymentPlanRouter = require("./routes/api/PaymentPlanRoute");
// const schedule = require("node-schedule");
const port = process.env.PORT || 3500;
const app = express();
// custom middleware logger
app.use(logger);
//middleware
app.use(credentials);
app.use(cookieParser());
app.use(cors(corsOptions));
app.set("trust proxy", true);
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
//serve static files
// console.log(path.join(__dirname, "/public"));
app.use("/public", express.static(path.join(__dirname, "/public")));
CronJob();
app.use("/", AuthRouter);
app.use("/", userRouter);
app.use("/", roleRouter);
app.use("/", resourceRouter);
app.use("/", teamRouter);
app.use("/", roleResourceRouter);
app.use("/", languageRouter);
app.use("/", articleRouter);
app.use("/", addressRouter);
app.use("/", unitRouter);
app.use("/", currencyRouter);
app.use("/", developerRouter);
app.use("/", categoryRouter);
app.use("/", announcementRouter);
app.use("/", aminitiesRouter);
app.use("/", propertyRouter);
app.use("/", guestRouter);
app.use("/", MetaDataRouter);
app.use("/", feedbackRouter);
app.use("/", enquiryFormRouter);
app.use("/", listwithusRouter);
app.use("/", jobRouter);
app.use("/", applicantRouter);
app.use("/", paymentPlanRouter);

app.use(errorHandler);
app.listen(port, () => {
	console.log(`Listening on port ${port}`);
});
