const resources = [
	{
		Name: "Property",
		Description: "Preoperties Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Article",
		Description: "Articles Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Team",
		Description: "Team Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Address",
		Description: "Address Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Currency",
		Description: "Currency Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Unit",
		Description: "Unit Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Images",
		Description: "Images Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Aminities",
		Description: "Aminities Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Category",
		Description: "Category Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Developer",
		Description: "Developer Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "PaymentPlan",
		Description: "PaymentPlan Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Resources",
		Description: "Resources Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Role-Resource",
		Description: "Role Resources Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Role",
		Description: "Role Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Users",
		Description: "Users Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Language",
		Description: "Language Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Developer",
		Description: "Developer Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Category",
		Description: "Category Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Announcement",
		Description: "Announcement Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Feedback",
		Description: "Feedback Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Enquiry",
		Description: "Enquiry Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Property",
		Description: "Property Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Job",
		Description: "Property Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Applicant",
		Description: "Applicant Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Guest-info",
		Description: "Guest info Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "List-with-us",
		Description: "List-with-us Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "Payment-Plan",
		Description: "Payment-Plan Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	{
		Name: "meta-Data",
		Description: "meta-Data Permission",
		ActiveStatus: true,
		CreatedAt: new Date(),
		UpdatedAt: new Date(),
	},
	// ToDo: meta-Data, Payment-Plan, list-with-us, Guest-info
];
module.exports = {
	resources,
};
